### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by ghost** [Sachaaaaaa/Grhoth#1]
Can't signin

**Comment by Sachaaaaaa** [comment]
Do you put your email or your username ?, if you put your username try with email.

**Comment by ghost** [comment]
Phone number

**Comment by ghost** [comment]
Phone number & email

**Comment by Sachaaaaaa** [comment]
try to connect to facebook normally to check if your account is not blocked

**Comment by ghost** [comment]
My account is not blocked..

**Comment by ghost** [comment]
New error after token generated

Traceback (most recent call last):
  File "Grhoth.py", line 317, in <module>
    mainj()
  File "Grhoth.py", line 71, in mainj
    load_token()
  File "Grhoth.py", line 17, in load_token
    main()
  File "Grhoth.py", line 21, in main
    ask = raw_input(name+W+"["+R+"="+W+"]")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

**Comment by Sachaaaaaa** [comment]
The problem must come from what is marked in the cookie\token.log file
